version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring

  mysql:
    image: mysql:5.7
    ports:
       - '3306:3306'
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    networks:
      - monitoring

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.0-latest
    ports:
      - '10051:10051'
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    depends_on:
      - mysql
    networks:
      - monitoring

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
    ports:
      - '8080:8080'
    environment:
      DB_SERVER_TYPE: mysql
      DB_SERVER_HOST: mysql
      DB_SERVER_PORT: 3306
      DB_SERVER_DBNAME: zabbix
      DB_SERVER_USER: zabbix
      DB_SERVER_PASS: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_SERVER_NAME: "Zabbix Server"
    depends_on:
      - mysql
      - zabbix-server
    networks:
      - monitoring

  go-server:
    build: ./go-server
    ports:
      - '8081:8080'
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
